---

# buildのtargetを指定したい = 3.4以上
version: "3.4"

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: bundle exec puma -C config/puma.rb
    environment:
      - RAILS_ENV=development
    ports:
      - 80:3000
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle

volumes:
  bundle_install:
    driver: local
