---

# buildのtargetを指定したい = 3.4以上
version: "3.4"

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: bundle exec puma -C config/puma.rb
    links:
      - mongodb:mongodb
      - mariadb:mariadb
    environment:
      - RAILS_ENV=development
    ports:
      - 80:3000
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle

  mongodb:
    image: mongo:4.0.6-xenial
    command: mongod --smallfiles
    environment:
      -  MONGODB_USER=user
      -  MONGODB_PASS=password!
    ports:
      - 27017:27017

#  mongo-express:
#    image: mongo-express:0.49.0
#    links:
#      - mongodb:mongo
#    ports:
#      - 8081:8081
#    environment:
#      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
#      - ME_CONFIG_BASICAUTH_USERNAME=user
#      - ME_CONFIG_BASICAUTH_PASSWORD=password!

  mariadb:
    image: mariadb:10.4.2-bionic
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - TZ=Asia/Tokyo
    ports:
      - 3306:3306

volumes:
  bundle_install:
    driver: local
