---

# buildのtargetを指定したい = 3.4以上
version: "3.4"

services:
  datastore:
    image: busybox
    volumes:
      - bundle_install:/app/vendor/bundle

  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    command: bundle exec puma -C config/puma.rb
    links:
      - mongodb:mongodb
    environment:
      - RAILS_ENV=development
    ports:
      - 80:3000
    volumes:
      - .:/app
      - bundle_install:/app/vendor/bundle

  mongodb:
    image: mongo:4.0.6-xenial
    command: mongod --smallfiles
    environment:
      -  MONGODB_USER=user
      -  MONGODB_PASS=password!
    ports:
      - 27017:27017

  mongo-express:
    image: mongo-express:0.49.0
    links:
      - mongodb:mongo
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_OPTIONS_EDITORTHEME=ambiance
      - ME_CONFIG_BASICAUTH_USERNAME=user
      - ME_CONFIG_BASICAUTH_PASSWORD=password!

volumes:
  bundle_install:
    driver: local
