---

# 自動deployに関して
# 1. herokuでAPI_KEYを発行(Acctoun settingsより発行可能)
# 2. CircleCIのダッシュボードよりEnvironment Variablesで環境変数を登録

version: 2

jobs:
  test:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: docker-compose build
          command: docker-compose build
      - run:
          name: docker-compose up
          command: docker-compose up -d
      - run:
          name: rspec
          command: docker-compose exec app bundle exec rspec
      - run:
          name: docker-compose down
          command: docker-compose down
  deploy:
    machine:
      image: circleci/classic:latest
    steps:
      - checkout
      - run:
          name: git push heroku master
          command: git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master

workflows:
  version: 2
  my_flows:
    jobs:
      - test
      - deploy:
          filters:
            branches:
              only: master
