mariadb_default: &mariadb_default
  adapter: mysql2
  encoding: utf8
  username: root
  password: password
  host: mariadb
  port: 3306
  pool: 5
  timeout: 5000

development:
  <<: *mariadb_default
  database: dice_development
everyday_rails_rspec_development:
  <<: *mariadb_default
  database: everyday_rails_rspec_development

test:
  <<: *mariadb_default
  database: dice_test
everyday_rails_rspec_test:
  <<: *mariadb_default
  database: everyday_rails_rspec_test

production:
  <<: *mariadb_default
  host: <%= ENV["DB_HOST"] %>
  database: <%= ENV["DB_DATABASE"] %>
  username: <%= ENV["DB_USERNAME"] %>
  password: <%= ENV["DB_PASSWORD"] %>
